name: test CI

on:
  push:
     branches: "main"
  pull_request:
     branches: "master"

jobs:
   frontend-test:
      runs-on: ubuntu-latest
      defaults:
         run:
            working-directory: ./quiz-app
            
